/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaGestorEmpleados;

/**
 *
 * @author Jokan5443
 */
public class AdministrarPagos extends javax.swing.JPanel {

    /**
     * Creates new form AdministrarPagos
     */
    public AdministrarPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPagoReg = new javax.swing.JPanel();
        lblIdPago = new javax.swing.JLabel();
        txtIdArea1 = new javax.swing.JTextField();
        btnCalcularPago = new javax.swing.JButton();
        lblTarifa = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        lblBono = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTarifa1 = new javax.swing.JTextField();
        txtTarifa2 = new javax.swing.JTextField();
        txtTarifa3 = new javax.swing.JTextField();
        txtTarifa5 = new javax.swing.JTextField();
        panelBusquedaPago = new javax.swing.JPanel();
        btnBuscarPago = new javax.swing.JButton();
        jsPagos = new javax.swing.JScrollPane();
        tbListaPagos = new javax.swing.JTable();
        jtBuscarPago = new javax.swing.JTabbedPane();
        panelIdBuscarArea = new javax.swing.JPanel();
        lblIDBuscar1 = new javax.swing.JLabel();
        txtIdBuscarPago = new javax.swing.JTextField();
        panelEstado = new javax.swing.JPanel();
        lblEstadoPago = new javax.swing.JLabel();
        listaEstadoBuscarPago = new javax.swing.JComboBox<>();
        lblBuscarOpc1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 153));

        panelPagoReg.setBackground(new java.awt.Color(0, 0, 0));
        panelPagoReg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nomina Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelPagoReg.setForeground(new java.awt.Color(0, 0, 0));

        lblIdPago.setForeground(new java.awt.Color(255, 255, 255));
        lblIdPago.setText("Id Empleado:");

        txtIdArea1.setBackground(new java.awt.Color(102, 102, 102));
        txtIdArea1.setForeground(new java.awt.Color(153, 153, 153));
        txtIdArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        btnCalcularPago.setText("Calcular");

        lblTarifa.setForeground(new java.awt.Color(255, 255, 255));
        lblTarifa.setText("Tarifa x Hora:");

        txtTarifa.setBackground(new java.awt.Color(102, 102, 102));
        txtTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifaActionPerformed(evt);
            }
        });

        lblBono.setForeground(new java.awt.Color(255, 255, 255));
        lblBono.setText("Bono:");

        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total a pagar:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HorasTrabajadas:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descuentos:");

        txtTarifa1.setBackground(new java.awt.Color(102, 102, 102));
        txtTarifa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifa1ActionPerformed(evt);
            }
        });

        txtTarifa2.setBackground(new java.awt.Color(102, 102, 102));
        txtTarifa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifa2ActionPerformed(evt);
            }
        });

        txtTarifa3.setBackground(new java.awt.Color(102, 102, 102));
        txtTarifa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifa3ActionPerformed(evt);
            }
        });

        txtTarifa5.setBackground(new java.awt.Color(102, 102, 102));
        txtTarifa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifa5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPagoRegLayout = new javax.swing.GroupLayout(panelPagoReg);
        panelPagoReg.setLayout(panelPagoRegLayout);
        panelPagoRegLayout.setHorizontalGroup(
            panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoRegLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcularPago)
                .addGap(15, 15, 15))
            .addGroup(panelPagoRegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPagoRegLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel2))
                        .addComponent(jLabel1)
                        .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBono)
                    .addComponent(lblIdPago))
                .addGap(18, 18, 18)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTarifa5)
                    .addComponent(txtTarifa2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTarifa3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoRegLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtTarifa1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPagoRegLayout.createSequentialGroup()
                        .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPagoRegLayout.setVerticalGroup(
            panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoRegLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarifa)
                    .addComponent(txtTarifa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarifa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarifa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnCalcularPago)
                .addGap(18, 18, 18)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTarifa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        panelBusquedaPago.setBackground(new java.awt.Color(0, 0, 0));
        panelBusquedaPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PanelBusqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnBuscarPago.setBackground(new java.awt.Color(0, 0, 153));
        btnBuscarPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscarPago.setText("Buscar");

        jsPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jsPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbListaPagos.setForeground(new java.awt.Color(0, 0, 0));
        tbListaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsPagos.setViewportView(tbListaPagos);

        jtBuscarPago.setToolTipText("");

        lblIDBuscar1.setText("Id Pago:");

        javax.swing.GroupLayout panelIdBuscarAreaLayout = new javax.swing.GroupLayout(panelIdBuscarArea);
        panelIdBuscarArea.setLayout(panelIdBuscarAreaLayout);
        panelIdBuscarAreaLayout.setHorizontalGroup(
            panelIdBuscarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarAreaLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIDBuscar1)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuscarPago, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(171, 171, 171))
        );
        panelIdBuscarAreaLayout.setVerticalGroup(
            panelIdBuscarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblIDBuscar1))
        );

        jtBuscarPago.addTab("ID", panelIdBuscarArea);

        lblEstadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoPago.setText("Estado laboral:");

        listaEstadoBuscarPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REALIZADO", "PENDIENTE" }));
        listaEstadoBuscarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEstadoBuscarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblEstadoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaEstadoBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGroup(panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaEstadoBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoPago))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtBuscarPago.addTab("Estado", panelEstado);

        lblBuscarOpc1.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarOpc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc1.setText("Buscar por(en blanco para todos):");

        javax.swing.GroupLayout panelBusquedaPagoLayout = new javax.swing.GroupLayout(panelBusquedaPago);
        panelBusquedaPago.setLayout(panelBusquedaPagoLayout);
        panelBusquedaPagoLayout.setHorizontalGroup(
            panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsPagos)
                    .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                        .addGroup(panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                                .addComponent(lblBuscarOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jtBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBusquedaPagoLayout.setVerticalGroup(
            panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                .addGroup(panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                        .addComponent(lblBuscarOpc1)
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPagoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBusquedaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(panelPagoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBusquedaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifaActionPerformed

    private void listaEstadoBuscarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEstadoBuscarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaEstadoBuscarPagoActionPerformed

    private void txtTarifa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifa1ActionPerformed

    private void txtTarifa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifa2ActionPerformed

    private void txtTarifa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifa3ActionPerformed

    private void txtTarifa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifa5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifa5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPago;
    private javax.swing.JButton btnCalcularPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jsPagos;
    private javax.swing.JTabbedPane jtBuscarPago;
    private javax.swing.JLabel lblBono;
    private javax.swing.JLabel lblBuscarOpc1;
    private javax.swing.JLabel lblEstadoPago;
    private javax.swing.JLabel lblIDBuscar1;
    private javax.swing.JLabel lblIdPago;
    private javax.swing.JLabel lblTarifa;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JComboBox<String> listaEstadoBuscarPago;
    private javax.swing.JPanel panelBusquedaPago;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelIdBuscarArea;
    private javax.swing.JPanel panelPagoReg;
    private javax.swing.JTable tbListaPagos;
    private javax.swing.JTextField txtIdArea1;
    private javax.swing.JTextField txtIdBuscarPago;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTarifa1;
    private javax.swing.JTextField txtTarifa2;
    private javax.swing.JTextField txtTarifa3;
    private javax.swing.JTextField txtTarifa5;
    // End of variables declaration//GEN-END:variables
}
