/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaGestorEmpleados;

import javax.swing.*;

/**
 *
 * @author User
 */
public class Areas extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Areas() {
        initComponents();
        
        Icon miIcono = new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/5-estrellas (2).png")).getImage().getScaledInstance(lbImagen.getWidth(), lbImagen.getHeight(), 0));
        
        lbImagen.setIcon(miIcono);
        lbImagen.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btnArchivo = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnAreas = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        btnGestionJerarquia = new javax.swing.JButton();
        btnGerente = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        lbImagen = new javax.swing.JLabel();
        CantEmpleados = new javax.swing.JPanel();
        lbCantEmpleados = new javax.swing.JLabel();
        CantJefes = new javax.swing.JPanel();
        lbCantJefes = new javax.swing.JLabel();
        CantSupervisores = new javax.swing.JPanel();
        lbCantSupervisores = new javax.swing.JLabel();
        CantPagosPendientes = new javax.swing.JPanel();
        lbCantPagosPendientes = new javax.swing.JLabel();
        CantPagosRealizados = new javax.swing.JPanel();
        lbCantPagosRealizados = new javax.swing.JLabel();
        CantAreas = new javax.swing.JPanel();
        lbCantAreas = new javax.swing.JLabel();
        TextoEmp1 = new javax.swing.JLabel();
        TextoEmp2 = new javax.swing.JLabel();
        TextoEmp3 = new javax.swing.JLabel();
        TextPagos1 = new javax.swing.JLabel();
        TextoPagos2 = new javax.swing.JLabel();
        TextoCantAreas = new javax.swing.JLabel();
        lblTextoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 135, 182));

        Menu.setBackground(new java.awt.Color(33, 44, 116));

        btnArchivo.setText("Archivo");

        btnEmpleados.setText("Empleados");

        btnAreas.setText("Areas");

        btnPagos.setText("Pagos");

        btnAsistencias.setText("Asistencias");

        btnGestionJerarquia.setLabel("Jerárquia");
        btnGestionJerarquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionJerarquiaActionPerformed(evt);
            }
        });

        btnGerente.setText("Gerente");

        btnReporte.setText("Reportes");

        btnAyuda.setText("Ayuda");

        lbImagen.setForeground(new java.awt.Color(255, 204, 153));
        lbImagen.setOpaque(true);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGestionJerarquia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArchivo)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados)
                .addGap(18, 18, 18)
                .addComponent(btnAreas)
                .addGap(18, 18, 18)
                .addComponent(btnPagos)
                .addGap(18, 18, 18)
                .addComponent(btnAsistencias)
                .addGap(18, 18, 18)
                .addComponent(btnGestionJerarquia)
                .addGap(18, 18, 18)
                .addComponent(btnGerente)
                .addGap(18, 18, 18)
                .addComponent(btnReporte)
                .addGap(18, 18, 18)
                .addComponent(btnAyuda)
                .addContainerGap())
        );

        lbCantEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantEmpleados.setForeground(new java.awt.Color(153, 153, 153));
        lbCantEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantEmpleados.setText("0");

        javax.swing.GroupLayout CantEmpleadosLayout = new javax.swing.GroupLayout(CantEmpleados);
        CantEmpleados.setLayout(CantEmpleadosLayout);
        CantEmpleadosLayout.setHorizontalGroup(
            CantEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCantEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CantEmpleadosLayout.setVerticalGroup(
            CantEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCantEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbCantJefes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantJefes.setForeground(new java.awt.Color(153, 153, 153));
        lbCantJefes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantJefes.setText("0");

        javax.swing.GroupLayout CantJefesLayout = new javax.swing.GroupLayout(CantJefes);
        CantJefes.setLayout(CantJefesLayout);
        CantJefesLayout.setHorizontalGroup(
            CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantJefesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantJefes, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantJefesLayout.setVerticalGroup(
            CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantJefesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantJefes, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lbCantSupervisores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantSupervisores.setForeground(new java.awt.Color(153, 153, 153));
        lbCantSupervisores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantSupervisores.setText("0");

        javax.swing.GroupLayout CantSupervisoresLayout = new javax.swing.GroupLayout(CantSupervisores);
        CantSupervisores.setLayout(CantSupervisoresLayout);
        CantSupervisoresLayout.setHorizontalGroup(
            CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantSupervisoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantSupervisores, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantSupervisoresLayout.setVerticalGroup(
            CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantSupervisoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantSupervisores, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lbCantPagosPendientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantPagosPendientes.setForeground(new java.awt.Color(153, 153, 153));
        lbCantPagosPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantPagosPendientes.setText("0");

        javax.swing.GroupLayout CantPagosPendientesLayout = new javax.swing.GroupLayout(CantPagosPendientes);
        CantPagosPendientes.setLayout(CantPagosPendientesLayout);
        CantPagosPendientesLayout.setHorizontalGroup(
            CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantPagosPendientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantPagosPendientesLayout.setVerticalGroup(
            CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantPagosPendientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lbCantPagosRealizados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantPagosRealizados.setForeground(new java.awt.Color(153, 153, 153));
        lbCantPagosRealizados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantPagosRealizados.setText("0");

        javax.swing.GroupLayout CantPagosRealizadosLayout = new javax.swing.GroupLayout(CantPagosRealizados);
        CantPagosRealizados.setLayout(CantPagosRealizadosLayout);
        CantPagosRealizadosLayout.setHorizontalGroup(
            CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantPagosRealizadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantPagosRealizadosLayout.setVerticalGroup(
            CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantPagosRealizadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lbCantAreas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantAreas.setForeground(new java.awt.Color(153, 153, 153));
        lbCantAreas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantAreas.setText("0");

        javax.swing.GroupLayout CantAreasLayout = new javax.swing.GroupLayout(CantAreas);
        CantAreas.setLayout(CantAreasLayout);
        CantAreasLayout.setHorizontalGroup(
            CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantAreasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantAreasLayout.setVerticalGroup(
            CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantAreasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        TextoEmp1.setText("Cantidad de empleados:");

        TextoEmp2.setText("Cantidad de Jefes:");

        TextoEmp3.setText("Cantidad de Supervisores:");

        TextPagos1.setText("Pagos Pendientes");

        TextoPagos2.setText("Pagos Realizados:");

        TextoCantAreas.setText("Cantidad de áreas:");

        lblTextoMenu.setBackground(new java.awt.Color(255, 51, 51));
        lblTextoMenu.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblTextoMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMenu.setText("Menú principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTextoMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextoEmp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(CantEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantJefes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoEmp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoEmp3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantSupervisores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCantAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CantPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextPagos1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TextoPagos2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(CantPagosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTextoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoEmp1)
                    .addComponent(TextoEmp2)
                    .addComponent(TextoEmp3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CantJefes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CantSupervisores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CantEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPagos1)
                    .addComponent(TextoPagos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantPagosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantPagosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(TextoCantAreas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionJerarquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionJerarquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionJerarquiaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CantAreas;
    private javax.swing.JPanel CantEmpleados;
    private javax.swing.JPanel CantJefes;
    private javax.swing.JPanel CantPagosPendientes;
    private javax.swing.JPanel CantPagosRealizados;
    private javax.swing.JPanel CantSupervisores;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel TextPagos1;
    private javax.swing.JLabel TextoCantAreas;
    private javax.swing.JLabel TextoEmp1;
    private javax.swing.JLabel TextoEmp2;
    private javax.swing.JLabel TextoEmp3;
    private javax.swing.JLabel TextoPagos2;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnAreas;
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnGerente;
    private javax.swing.JButton btnGestionJerarquia;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCantAreas;
    private javax.swing.JLabel lbCantEmpleados;
    private javax.swing.JLabel lbCantJefes;
    private javax.swing.JLabel lbCantPagosPendientes;
    private javax.swing.JLabel lbCantPagosRealizados;
    private javax.swing.JLabel lbCantSupervisores;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lblTextoMenu;
    // End of variables declaration//GEN-END:variables
}
