/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaGestorEmpleados;

import GestionEmpleados.GestorEmpleados;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MenuEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    public static final List<String[]> empleados = new ArrayList<>();
    public static final GestorEmpleados gestor = new GestorEmpleados();
    
    public MenuEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Agregar Icono
        Icon miIcono = new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/5-estrellas (2).png")).getImage().getScaledInstance(lbImagen.getWidth(), lbImagen.getHeight(), 0));
        lbImagen.setIcon(miIcono);
        lbImagen.setOpaque(false);
        
        actualizarTabla();
    }
    
    public void registrarEmpleado(){
        String datos[] = {txtIdEmpleado.getText(), txtNombre.getText(), txtApellido.getText(), txtCorreo.getText(), txtCorreo.getText(),
        "HOY", "MAÑANA", "PASADO",
        "Activo", "Permanente", (String)listaCargos.getSelectedItem(),
        txtArea.getText(), "0.10",
        "1"};
        

        
        empleados.add(datos);
        
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        //Definir modelo
        DefaultTableModel modeloOperario = new DefaultTableModel();
        
        modeloOperario.setColumnIdentifiers(new String[]{
        "Id", "Nombre", "Apellido", "Email", "DNI",
        "Fecha ingreso", "Fecha Termino", "Fecha renovación",
        "Estado laboral", "Tipo Contrato", "Cargo",
        "Area", "Tarifa",
        "Id Jefe"});
        
        for(String[] dato: empleados){
            modeloOperario.addRow(dato);
        }
        
        tbLista.setModel(modeloOperario);
        
        txtTarifa.setEditable(false);
        txtBono.setEditable(false);
        txtTotalPagar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btnArchivo = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnAreas = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        btnGestionJerarquia = new javax.swing.JButton();
        btnGerente = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        lbImagen = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMenu = new javax.swing.JPanel();
        CantEmpleados = new javax.swing.JPanel();
        lbCantEmpleados = new javax.swing.JLabel();
        CantJefes = new javax.swing.JPanel();
        lbCantJefes = new javax.swing.JLabel();
        CantSupervisores = new javax.swing.JPanel();
        lbCantSupervisores = new javax.swing.JLabel();
        CantPagosPendientes = new javax.swing.JPanel();
        lbCantPagosPendientes = new javax.swing.JLabel();
        CantPagosRealizados = new javax.swing.JPanel();
        lbCantPagosRealizados = new javax.swing.JLabel();
        CantAreas = new javax.swing.JPanel();
        lbCantAreas = new javax.swing.JLabel();
        TextoEmp1 = new javax.swing.JLabel();
        txtCantJefes = new javax.swing.JLabel();
        TextoEmp3 = new javax.swing.JLabel();
        txtPagosPend = new javax.swing.JLabel();
        txtPagosReal = new javax.swing.JLabel();
        TextoCantAreas = new javax.swing.JLabel();
        lblTextoMenu = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        panelSoloEmpl = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnModifiar = new javax.swing.JButton();
        panelAreas = new javax.swing.JPanel();
        lblIdArea = new javax.swing.JLabel();
        txtIdArea = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnBuscarArea = new javax.swing.JButton();
        panelCargos = new javax.swing.JPanel();
        lblCargo = new javax.swing.JLabel();
        listaCargos = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        panelBusqueda = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jsEmpleados = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jtBuscar = new javax.swing.JTabbedPane();
        panelIdBuscar = new javax.swing.JPanel();
        lblIDBuscar = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        panelAreaBuscar = new javax.swing.JPanel();
        lbIdAreaBuscar = new javax.swing.JLabel();
        txtIdAreaBuscar = new javax.swing.JTextField();
        panelEstadoLaboralBuscar = new javax.swing.JPanel();
        lblEstadoBuscar = new javax.swing.JLabel();
        listaEstadoBuscar = new javax.swing.JComboBox<>();
        lblBuscarOpc = new javax.swing.JLabel();
        panelArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdAreaRegistrar = new javax.swing.JTextField();
        txtNombreArea = new javax.swing.JTextField();
        btnRegistrarArea = new javax.swing.JButton();
        btnEliminarArea = new javax.swing.JButton();
        btnEditarArea = new javax.swing.JButton();
        btnListarArea = new javax.swing.JButton();
        scrollAreas = new javax.swing.JScrollPane();
        tablaAreas = new javax.swing.JTable();
        panelPagos = new javax.swing.JPanel();
        panelPagosEmp = new javax.swing.JPanel();
        lbID1 = new javax.swing.JLabel();
        txtIdEmpleadoPago = new javax.swing.JTextField();
        lbNombre1 = new javax.swing.JLabel();
        txtNomEmpPago = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApEmpPago = new javax.swing.JTextField();
        lblDni1 = new javax.swing.JLabel();
        txtDNIPago = new javax.swing.JTextField();
        lblCorreo1 = new javax.swing.JLabel();
        txtCorreoPago = new javax.swing.JTextField();
        btnBuscarEmpPago = new javax.swing.JButton();
        panelPagoReg = new javax.swing.JPanel();
        lblIdPago = new javax.swing.JLabel();
        txtIdArea1 = new javax.swing.JTextField();
        btnCalcularPago = new javax.swing.JButton();
        lblTarifa = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        lblBono = new javax.swing.JLabel();
        txtBono = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        btnRegistrarPago = new javax.swing.JButton();
        panelBusquedaPago = new javax.swing.JPanel();
        btnBuscarPago = new javax.swing.JButton();
        jsPagos = new javax.swing.JScrollPane();
        tbListaPagos = new javax.swing.JTable();
        jtBuscarPago = new javax.swing.JTabbedPane();
        panelIdBuscarArea = new javax.swing.JPanel();
        lblIDBuscar1 = new javax.swing.JLabel();
        txtIdBuscarPago = new javax.swing.JTextField();
        panelEstado = new javax.swing.JPanel();
        lblEstadoPago = new javax.swing.JLabel();
        listaEstadoBuscarPago = new javax.swing.JComboBox<>();
        lblBuscarOpc1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(128, 135, 182));

        Menu.setBackground(new java.awt.Color(33, 44, 116));

        btnArchivo.setText("Archivo");

        btnEmpleados.setText("Empleados");

        btnAreas.setText("Areas");

        btnPagos.setText("Pagos");

        btnAsistencias.setText("Asistencias");

        btnGestionJerarquia.setLabel("Jerárquia");
        btnGestionJerarquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionJerarquiaActionPerformed(evt);
            }
        });

        btnGerente.setText("Gerente");

        btnReporte.setText("Reportes");

        btnAyuda.setText("Ayuda");

        lbImagen.setForeground(new java.awt.Color(255, 204, 153));
        lbImagen.setOpaque(true);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGestionJerarquia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnArchivo)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados)
                .addGap(18, 18, 18)
                .addComponent(btnAreas)
                .addGap(18, 18, 18)
                .addComponent(btnPagos)
                .addGap(18, 18, 18)
                .addComponent(btnAsistencias)
                .addGap(18, 18, 18)
                .addComponent(btnGestionJerarquia)
                .addGap(18, 18, 18)
                .addComponent(btnGerente)
                .addGap(18, 18, 18)
                .addComponent(btnReporte)
                .addGap(18, 18, 18)
                .addComponent(btnAyuda)
                .addContainerGap())
        );

        panelMenu.setName("Menu"); // NOI18N

        CantEmpleados.setBackground(new java.awt.Color(255, 255, 255));

        lbCantEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantEmpleados.setForeground(new java.awt.Color(153, 153, 153));
        lbCantEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantEmpleados.setText("0");

        javax.swing.GroupLayout CantEmpleadosLayout = new javax.swing.GroupLayout(CantEmpleados);
        CantEmpleados.setLayout(CantEmpleadosLayout);
        CantEmpleadosLayout.setHorizontalGroup(
            CantEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCantEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        CantEmpleadosLayout.setVerticalGroup(
            CantEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCantEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        CantJefes.setBackground(new java.awt.Color(255, 255, 255));

        lbCantJefes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantJefes.setForeground(new java.awt.Color(153, 153, 153));
        lbCantJefes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantJefes.setText("0");

        javax.swing.GroupLayout CantJefesLayout = new javax.swing.GroupLayout(CantJefes);
        CantJefes.setLayout(CantJefesLayout);
        CantJefesLayout.setHorizontalGroup(
            CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantJefesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantJefes, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantJefesLayout.setVerticalGroup(
            CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CantJefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantJefesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantJefes, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        CantSupervisores.setBackground(new java.awt.Color(255, 255, 255));

        lbCantSupervisores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantSupervisores.setForeground(new java.awt.Color(153, 153, 153));
        lbCantSupervisores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantSupervisores.setText("0");

        javax.swing.GroupLayout CantSupervisoresLayout = new javax.swing.GroupLayout(CantSupervisores);
        CantSupervisores.setLayout(CantSupervisoresLayout);
        CantSupervisoresLayout.setHorizontalGroup(
            CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantSupervisoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantSupervisores, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantSupervisoresLayout.setVerticalGroup(
            CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CantSupervisoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantSupervisoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantSupervisores, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        CantPagosPendientes.setBackground(new java.awt.Color(255, 255, 255));

        lbCantPagosPendientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantPagosPendientes.setForeground(new java.awt.Color(153, 153, 153));
        lbCantPagosPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantPagosPendientes.setText("0");

        javax.swing.GroupLayout CantPagosPendientesLayout = new javax.swing.GroupLayout(CantPagosPendientes);
        CantPagosPendientes.setLayout(CantPagosPendientesLayout);
        CantPagosPendientesLayout.setHorizontalGroup(
            CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantPagosPendientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantPagosPendientesLayout.setVerticalGroup(
            CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantPagosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantPagosPendientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        CantPagosRealizados.setBackground(new java.awt.Color(255, 255, 255));

        lbCantPagosRealizados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantPagosRealizados.setForeground(new java.awt.Color(153, 153, 153));
        lbCantPagosRealizados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantPagosRealizados.setText("0");

        javax.swing.GroupLayout CantPagosRealizadosLayout = new javax.swing.GroupLayout(CantPagosRealizados);
        CantPagosRealizados.setLayout(CantPagosRealizadosLayout);
        CantPagosRealizadosLayout.setHorizontalGroup(
            CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantPagosRealizadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantPagosRealizadosLayout.setVerticalGroup(
            CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantPagosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantPagosRealizadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantPagosRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        CantAreas.setBackground(new java.awt.Color(255, 255, 255));

        lbCantAreas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCantAreas.setForeground(new java.awt.Color(153, 153, 153));
        lbCantAreas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantAreas.setText("0");

        javax.swing.GroupLayout CantAreasLayout = new javax.swing.GroupLayout(CantAreas);
        CantAreas.setLayout(CantAreasLayout);
        CantAreasLayout.setHorizontalGroup(
            CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CantAreasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CantAreasLayout.setVerticalGroup(
            CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CantAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantAreasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCantAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        TextoEmp1.setText("Cantidad de empleados:");

        txtCantJefes.setText("Cantidad de Jefes:");

        TextoEmp3.setText("Cantidad de Supervisores:");

        txtPagosPend.setText("Pagos Pendientes");

        txtPagosReal.setText("Pagos Realizados:");

        TextoCantAreas.setText("Cantidad de áreas:");

        lblTextoMenu.setBackground(new java.awt.Color(255, 51, 51));
        lblTextoMenu.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblTextoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMenu.setText("Menú principal");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCantAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextoEmp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CantEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CantPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPagosPend, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CantJefes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantJefes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPagosReal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantPagosRealizados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoEmp3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantSupervisores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lblTextoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoEmp1)
                    .addComponent(txtCantJefes)
                    .addComponent(TextoEmp3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CantJefes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CantSupervisores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CantEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPagosPend)
                    .addComponent(txtPagosReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantPagosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantPagosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(TextoCantAreas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(lblTextoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(335, 335, 335)))
        );

        jTabbedPane1.addTab("Menu", panelMenu);

        panelSoloEmpl.setBackground(new java.awt.Color(255, 255, 255));
        panelSoloEmpl.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));

        lbID.setText("ID:");

        lbNombre.setText("Nombre:");

        lblApellido.setText("Apellido:");

        lblDni.setText("DNI:");

        lblCorreo.setText("Correo:");

        btnModifiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModifiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-del-portapapeles.png"))); // NOI18N
        btnModifiar.setText("Modificar datos");

        javax.swing.GroupLayout panelSoloEmplLayout = new javax.swing.GroupLayout(panelSoloEmpl);
        panelSoloEmpl.setLayout(panelSoloEmplLayout);
        panelSoloEmplLayout.setHorizontalGroup(
            panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoloEmplLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSoloEmplLayout.createSequentialGroup()
                        .addComponent(btnModifiar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(panelSoloEmplLayout.createSequentialGroup()
                        .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre)
                            .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtIdEmpleado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSoloEmplLayout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addGap(22, 22, 22)
                        .addComponent(txtCorreo))
                    .addGroup(panelSoloEmplLayout.createSequentialGroup()
                        .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido)
                            .addComponent(lblDni))
                        .addGap(12, 12, 12)
                        .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI)
                            .addComponent(txtApellido))))
                .addContainerGap())
        );
        panelSoloEmplLayout.setVerticalGroup(
            panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoloEmplLayout.createSequentialGroup()
                .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSoloEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifiar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE))
        );

        panelAreas.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas.setBorder(javax.swing.BorderFactory.createTitledBorder("Áreas"));

        lblIdArea.setText("ID:");

        lblArea.setText("Area:");

        btnBuscarArea.setText("...");
        btnBuscarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAreasLayout = new javax.swing.GroupLayout(panelAreas);
        panelAreas.setLayout(panelAreasLayout);
        panelAreasLayout.setHorizontalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addComponent(lblIdArea)
                        .addGap(28, 28, 28)
                        .addComponent(txtIdArea))
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addGap(18, 18, 18)
                        .addComponent(txtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addComponent(btnBuscarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAreasLayout.setVerticalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addComponent(btnBuscarArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArea)
                    .addComponent(txtIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelCargos.setBackground(new java.awt.Color(255, 255, 255));
        panelCargos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargos"));

        lblCargo.setText("Cargo:");

        listaCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operario", "Supervisor", "Jefe" }));

        javax.swing.GroupLayout panelCargosLayout = new javax.swing.GroupLayout(panelCargos);
        panelCargos.setLayout(panelCargosLayout);
        panelCargosLayout.setHorizontalGroup(
            panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCargo)
                .addGap(18, 18, 18)
                .addComponent(listaCargos, 0, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCargosLayout.setVerticalGroup(
            panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(listaCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escritura.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("PanelBusqueda"));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        jsEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Empleados"));
        jsEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsEmpleados.setViewportView(tbLista);

        jtBuscar.setToolTipText("");

        lblIDBuscar.setText("Id Empleado:");

        javax.swing.GroupLayout panelIdBuscarLayout = new javax.swing.GroupLayout(panelIdBuscar);
        panelIdBuscar.setLayout(panelIdBuscarLayout);
        panelIdBuscarLayout.setHorizontalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIDBuscar)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(171, 171, 171))
        );
        panelIdBuscarLayout.setVerticalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblIDBuscar))
        );

        jtBuscar.addTab("ID", panelIdBuscar);

        lbIdAreaBuscar.setText("Id Area: ");

        javax.swing.GroupLayout panelAreaBuscarLayout = new javax.swing.GroupLayout(panelAreaBuscar);
        panelAreaBuscar.setLayout(panelAreaBuscarLayout);
        panelAreaBuscarLayout.setHorizontalGroup(
            panelAreaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaBuscarLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(lbIdAreaBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdAreaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(166, 166, 166))
        );
        panelAreaBuscarLayout.setVerticalGroup(
            panelAreaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdAreaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbIdAreaBuscar))
        );

        jtBuscar.addTab("Area", panelAreaBuscar);

        lblEstadoBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoBuscar.setText("Estado laboral:");

        listaEstadoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "DESPEDIDO" }));

        javax.swing.GroupLayout panelEstadoLaboralBuscarLayout = new javax.swing.GroupLayout(panelEstadoLaboralBuscar);
        panelEstadoLaboralBuscar.setLayout(panelEstadoLaboralBuscarLayout);
        panelEstadoLaboralBuscarLayout.setHorizontalGroup(
            panelEstadoLaboralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLaboralBuscarLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblEstadoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelEstadoLaboralBuscarLayout.setVerticalGroup(
            panelEstadoLaboralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLaboralBuscarLayout.createSequentialGroup()
                .addGroup(panelEstadoLaboralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoBuscar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtBuscar.addTab("Estado", panelEstadoLaboralBuscar);

        lblBuscarOpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc.setText("Buscar por(en blanco para todos):");

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsEmpleados)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBusquedaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBusquedaLayout.createSequentialGroup()
                                .addComponent(lblBuscarOpc, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblBuscarOpc)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addComponent(panelSoloEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panelAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(panelCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSoloEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addComponent(panelCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleados", panelEmpleados);

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        btnRegistrarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escritura.png"))); // NOI18N
        btnRegistrarArea.setText("Registrar");

        btnEliminarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ocultar.png"))); // NOI18N
        btnEliminarArea.setText("Eliminar");

        btnEditarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-del-portapapeles.png"))); // NOI18N
        btnEditarArea.setText("Editar");

        btnListarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnListarArea.setText("Listar");

        tablaAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAreas.setViewportView(tablaAreas);

        javax.swing.GroupLayout panelAreaLayout = new javax.swing.GroupLayout(panelArea);
        panelArea.setLayout(panelAreaLayout);
        panelAreaLayout.setHorizontalGroup(
            panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarArea, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRegistrarArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdAreaRegistrar)
                        .addComponent(txtNombreArea)
                        .addComponent(btnEditarArea, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(btnListarArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAreaLayout.setVerticalGroup(
            panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdAreaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnRegistrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(scrollAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Areas", panelArea);

        panelPagosEmp.setBackground(new java.awt.Color(255, 255, 255));
        panelPagosEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));

        lbID1.setText("ID:");

        lbNombre1.setText("Nombre:");

        lblApellido1.setText("Apellido:");

        lblDni1.setText("DNI:");

        lblCorreo1.setText("Correo:");

        btnBuscarEmpPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarEmpPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscarEmpPago.setText("Buscar");

        javax.swing.GroupLayout panelPagosEmpLayout = new javax.swing.GroupLayout(panelPagosEmp);
        panelPagosEmp.setLayout(panelPagosEmpLayout);
        panelPagosEmpLayout.setHorizontalGroup(
            panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosEmpLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagosEmpLayout.createSequentialGroup()
                        .addComponent(btnBuscarEmpPago, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(panelPagosEmpLayout.createSequentialGroup()
                        .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre1)
                            .addComponent(lbID1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomEmpPago)
                            .addComponent(txtIdEmpleadoPago)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagosEmpLayout.createSequentialGroup()
                        .addComponent(lblCorreo1)
                        .addGap(22, 22, 22)
                        .addComponent(txtCorreoPago))
                    .addGroup(panelPagosEmpLayout.createSequentialGroup()
                        .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido1)
                            .addComponent(lblDni1))
                        .addGap(12, 12, 12)
                        .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNIPago)
                            .addComponent(txtApEmpPago))))
                .addContainerGap())
        );
        panelPagosEmpLayout.setVerticalGroup(
            panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosEmpLayout.createSequentialGroup()
                .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID1)
                    .addComponent(txtIdEmpleadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre1)
                    .addComponent(txtNomEmpPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1)
                    .addComponent(txtApEmpPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni1)
                    .addComponent(txtDNIPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo1)
                    .addComponent(txtCorreoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarEmpPago, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE))
        );

        panelPagoReg.setBackground(new java.awt.Color(255, 255, 255));
        panelPagoReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Nomina Pago"));

        lblIdPago.setText("Id pago:");

        btnCalcularPago.setText("Calcular");

        lblTarifa.setText("Tarifa:");

        lblBono.setText("Bono:");

        lblTotal.setText("Total a pagar:");

        javax.swing.GroupLayout panelPagoRegLayout = new javax.swing.GroupLayout(panelPagoReg);
        panelPagoReg.setLayout(panelPagoRegLayout);
        panelPagoRegLayout.setHorizontalGroup(
            panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoRegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoRegLayout.createSequentialGroup()
                        .addComponent(lblIdPago)
                        .addGap(28, 28, 28)
                        .addComponent(txtIdArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addGroup(panelPagoRegLayout.createSequentialGroup()
                        .addComponent(lblBono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBono, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoRegLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(panelPagoRegLayout.createSequentialGroup()
                        .addComponent(lblTarifa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addGroup(panelPagoRegLayout.createSequentialGroup()
                        .addComponent(btnCalcularPago)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPagoRegLayout.setVerticalGroup(
            panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoRegLayout.createSequentialGroup()
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPago)
                    .addComponent(txtIdArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarifa)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBono)
                    .addComponent(txtBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnRegistrarPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escritura.png"))); // NOI18N
        btnRegistrarPago.setText("Registrar");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        panelBusquedaPago.setBackground(new java.awt.Color(255, 255, 255));
        panelBusquedaPago.setBorder(javax.swing.BorderFactory.createTitledBorder("PanelBusqueda"));

        btnBuscarPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscarPago.setText("Buscar");

        jsPagos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Empleados"));
        jsPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbListaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsPagos.setViewportView(tbListaPagos);

        jtBuscarPago.setToolTipText("");

        lblIDBuscar1.setText("Id Pago:");

        javax.swing.GroupLayout panelIdBuscarAreaLayout = new javax.swing.GroupLayout(panelIdBuscarArea);
        panelIdBuscarArea.setLayout(panelIdBuscarAreaLayout);
        panelIdBuscarAreaLayout.setHorizontalGroup(
            panelIdBuscarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarAreaLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIDBuscar1)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuscarPago, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(171, 171, 171))
        );
        panelIdBuscarAreaLayout.setVerticalGroup(
            panelIdBuscarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblIDBuscar1))
        );

        jtBuscarPago.addTab("ID", panelIdBuscarArea);

        lblEstadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoPago.setText("Estado laboral:");

        listaEstadoBuscarPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REALIZADO", "PENDIENTE" }));

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblEstadoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaEstadoBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGroup(panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaEstadoBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoPago))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtBuscarPago.addTab("Estado", panelEstado);

        lblBuscarOpc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc1.setText("Buscar por(en blanco para todos):");

        javax.swing.GroupLayout panelBusquedaPagoLayout = new javax.swing.GroupLayout(panelBusquedaPago);
        panelBusquedaPago.setLayout(panelBusquedaPagoLayout);
        panelBusquedaPagoLayout.setHorizontalGroup(
            panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsPagos)
                    .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                        .addGroup(panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                                .addComponent(lblBuscarOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jtBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBusquedaPagoLayout.setVerticalGroup(
            panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                .addGroup(panelBusquedaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaPagoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblBuscarOpc1)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPagosLayout = new javax.swing.GroupLayout(panelPagos);
        panelPagos.setLayout(panelPagosLayout);
        panelPagosLayout.setHorizontalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagosLayout.createSequentialGroup()
                        .addComponent(panelPagosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelPagoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagosLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(panelBusquedaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPagosLayout.setVerticalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPagosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelPagoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBusquedaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagos", panelPagos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabCambio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionJerarquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionJerarquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionJerarquiaActionPerformed

    private void btnBuscarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAreaActionPerformed

    }//GEN-LAST:event_btnBuscarAreaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarEmpleado();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CantAreas;
    private javax.swing.JPanel CantEmpleados;
    private javax.swing.JPanel CantJefes;
    private javax.swing.JPanel CantPagosPendientes;
    private javax.swing.JPanel CantPagosRealizados;
    private javax.swing.JPanel CantSupervisores;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel TextoCantAreas;
    private javax.swing.JLabel TextoEmp1;
    private javax.swing.JLabel TextoEmp3;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnAreas;
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarArea;
    private javax.swing.JButton btnBuscarEmpPago;
    private javax.swing.JButton btnBuscarPago;
    private javax.swing.JButton btnCalcularPago;
    private javax.swing.JButton btnEditarArea;
    private javax.swing.JButton btnEliminarArea;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnGerente;
    private javax.swing.JButton btnGestionJerarquia;
    private javax.swing.JButton btnListarArea;
    private javax.swing.JButton btnModifiar;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarArea;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jsEmpleados;
    private javax.swing.JScrollPane jsPagos;
    private javax.swing.JTabbedPane jtBuscar;
    private javax.swing.JTabbedPane jtBuscarPago;
    private javax.swing.JLabel lbCantAreas;
    private javax.swing.JLabel lbCantEmpleados;
    private javax.swing.JLabel lbCantJefes;
    private javax.swing.JLabel lbCantPagosPendientes;
    private javax.swing.JLabel lbCantPagosRealizados;
    private javax.swing.JLabel lbCantSupervisores;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbID1;
    private javax.swing.JLabel lbIdAreaBuscar;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBono;
    private javax.swing.JLabel lblBuscarOpc;
    private javax.swing.JLabel lblBuscarOpc1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblEstadoBuscar;
    private javax.swing.JLabel lblEstadoPago;
    private javax.swing.JLabel lblIDBuscar;
    private javax.swing.JLabel lblIDBuscar1;
    private javax.swing.JLabel lblIdArea;
    private javax.swing.JLabel lblIdPago;
    private javax.swing.JLabel lblTarifa;
    private javax.swing.JLabel lblTextoMenu;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JComboBox<String> listaCargos;
    private javax.swing.JComboBox<String> listaEstadoBuscar;
    private javax.swing.JComboBox<String> listaEstadoBuscarPago;
    private javax.swing.JPanel panelArea;
    private javax.swing.JPanel panelAreaBuscar;
    private javax.swing.JPanel panelAreas;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelBusquedaPago;
    private javax.swing.JPanel panelCargos;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelEstadoLaboralBuscar;
    private javax.swing.JPanel panelIdBuscar;
    private javax.swing.JPanel panelIdBuscarArea;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPagoReg;
    private javax.swing.JPanel panelPagos;
    private javax.swing.JPanel panelPagosEmp;
    private javax.swing.JPanel panelSoloEmpl;
    private javax.swing.JScrollPane scrollAreas;
    private javax.swing.JTable tablaAreas;
    private javax.swing.JTable tbLista;
    private javax.swing.JTable tbListaPagos;
    private javax.swing.JTextField txtApEmpPago;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBono;
    private javax.swing.JLabel txtCantJefes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoPago;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNIPago;
    private javax.swing.JTextField txtIdArea;
    private javax.swing.JTextField txtIdArea1;
    private javax.swing.JTextField txtIdAreaBuscar;
    private javax.swing.JTextField txtIdAreaRegistrar;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtIdBuscarPago;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdEmpleadoPago;
    private javax.swing.JTextField txtNomEmpPago;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArea;
    private javax.swing.JLabel txtPagosPend;
    private javax.swing.JLabel txtPagosReal;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
