
package VistaHotel;

import javax.swing.JOptionPane;


public class ServicioAdicional extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public ServicioAdicional() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTextField12 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(33, 44, 116));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setBackground(new java.awt.Color(33, 44, 116));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 170, 20));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CLIENTE");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DNI");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 30));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CATEGORIA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 30));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DETALLE VENTA");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 170, 10));

        jTextField6.setBackground(new java.awt.Color(33, 44, 116));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(null);
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 170, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, 10));

        jTextField7.setBackground(new java.awt.Color(33, 44, 116));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setBorder(null);
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, 20));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, 10));

        jTextField8.setBackground(new java.awt.Color(33, 44, 116));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setBorder(null);
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, 20));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, 10));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("N. HABITACION");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TELEFONO");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));

        jTextField9.setBackground(new java.awt.Color(33, 44, 116));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(null);
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 20));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, 10));

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("RESUMEN DE LA HABITACION");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "PRECIO UNITARIO", "SUB. TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 710, 90));

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CANTIDAD");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PRECIO");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 30));

        jTextField11.setBackground(new java.awt.Color(33, 44, 116));
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setBorder(null);
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 170, 20));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 170, 10));

        jTextField12.setBackground(new java.awt.Color(33, 44, 116));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setBorder(null);
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, 20));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 170, 10));

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PRODUCTO");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        jButton3.setBackground(new java.awt.Color(33, 44, 116));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("FINALIZAR VENTA");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 150, 30));

        jComboBox1.setBackground(new java.awt.Color(33, 44, 116));
        jComboBox1.setEditable(true);
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, 20));

        jTextField10.setBackground(new java.awt.Color(33, 44, 116));
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setBorder(null);
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 170, 20));

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TOTAL A PAGAR");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 380, 120, 30));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 170, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 170, 10));

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ESTADO DE VENTA");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 150, 20));

        jComboBox2.setBackground(new java.awt.Color(33, 44, 116));
        jComboBox2.setEditable(true);
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Cancelado" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 170, 20));

        jButton4.setBackground(new java.awt.Color(33, 44, 116));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("AGREGAR");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, 30));
    }// </editor-fold>//GEN-END:initComponents
/*---------------------colocar en otro lado------------------------------------*/
private void mostrarMensajeExito() {
    JOptionPane.showMessageDialog(null, "La venta fue registrada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
